### ISSUE TITLE
Blank default settings on OSX.

### ISSUE THREAD

**Issue by dgorodnichy** [ArtificalSUN/Kcalibrator#14]
When I launch Kcalibrator on OSX I don't see any default settings. All select lists are also blank. Because of this, I can't choose values in these fields. When I fill remain settings manually and click on "Generate G code" I don't see any actions. Code is not generated

<img width="823" alt="Снимок экрана 2021-07-23 в 08 58 00 1" src="https://user-images.githubusercontent.com/53345298/126742628-047391b5-8dac-4e62-9f2c-9054acfd73e7.png">
 <img width="658" alt="Снимок экрана 2021-07-23 в 08 51 15" src="https://user-images.githubusercontent.com/53345298/126742190-f454e068-932a-41af-b24b-167d937565ce.png">

**Comment by dgorodnichy** [comment]
The same behaviour for Windows:
 
<img width="760" alt="Снимок экрана 2021-07-23 в 09 17 06" src="https://user-images.githubusercontent.com/53345298/126744105-b0360086-4269-453f-aad1-c4ec386a1819.png">

**Comment by ArtificalSUN** [comment]
You have to run kcalibrator.pyw, not kcalibrator_gui.py.
I will update the README to make it more clear.

**Comment by dgorodnichy** [comment]
Thanks for a quick answer. It helped!
![image](https://user-images.githubusercontent.com/53345298/126765387-9b0190ac-a600-4f05-942d-e2815d47a5a1.png)
