### ISSUE TITLE
Last move purge more filament than needed

### ISSUE THREAD

**Issue by Ogurezzz** [ArtificalSUN/Kcalibrator#16]
Last move should purge 3,12063mm of filament (height 0.3 width 0.6) But it extrude 5,21603.
Is it feature or bug?

M117 K=0.000
G0 X117.500 Y152.500 Z0.600 F12000.0
G1 X75.500 Y152.500 Z0.600 E3.14308 F600.0
G1 X47.500 Y152.500 Z0.600 E5.23847 F2700.0
G1 X47.500 Y117.500 Z0.600 E7.85771 F2700.0
G1 X47.500 Y82.500 Z0.600 E10.47694 F600.0
G1 X75.500 Y82.500 Z0.600 E12.57233 F600.0
G1 X159.500 Y82.500 Z0.600 E18.85850 F2700.0
G1 X187.500 Y82.500 Z0.600 E20.95389 F600.0
G1 X187.500 Y117.500 Z0.600 E23.57312 F600.0
G1 X187.500 Y152.500 Z0.600 E26.19236 F2700.0
G1 X159.500 Y152.500 Z0.600 E28.28774 F2700.0
G1 X117.800 Y152.500 Z0.600 E33.50377 F600.0
G92 E0

**Comment by ArtificalSUN** [comment]
Fixed
