### ISSUE TITLE
Ошибка в расчете экструзии

### ISSUE THREAD

**Issue by Kost38** [ArtificalSUN/Kcalibrator#20]
Приветствую, Виктор!
У вас какая-то ошибка в расчете экструзии на последнем сегменте перед швом.
G1 X192.000 Y185.000 Z9.400 E12.57233 F7200.0
G1 X150.200 Y185.000 Z9.400 E14.89389 F2400.0 #Экструзия 2.3 мм на 42 мм сегмент
G92 E0
G1 E-0.8 F1800.0
G0 X150.000 Y185.000 Z9.600 F9600.0
G1 E0 F1800.0
G1 X108.000 Y185.000 Z9.600 E1.39693 F2400.0 #Экструзия 1.4 на 42 мм, это больше похоже на правду

**Comment by SantinoDnepr** [comment]
Добрый день, Виктор.
Подтверждаю, есть проблема с экструзией на задней стенке. Прикладываю файлы с изображениями распечаток. Обе распечатки пластиком ABS, параметры печати на скрине "Image 1.png". В файле "Image 2.png" скрин с просмотрщика g-code c показом объемного расхода. 
![Image 1](https://user-images.githubusercontent.com/24602516/159058955-7b467dc2-609b-4fd1-9c32-0b18b0ae71f3.png)
![Image 2](https://user-images.githubusercontent.com/24602516/159058962-f391c5dd-a69c-4e41-af40-4e7e77a72d13.png)
![20220318_194032](https://user-images.githubusercontent.com/24602516/159058985-a801eb60-38d8-4276-8f8c-bd1818aa0d38.jpg)
![20220318_194058](https://user-images.githubusercontent.com/24602516/159058993-c945c5b4-5cff-4547-8f41-8340d74d511b.jpg)
[KF_0.0-0.1-0.01_H245-B108.zip](https://github.com/ArtificalSUN/Kcalibrator/files/8306708/KF_0.0-0.1-0.01_H245-B108.zip)

**Comment by ArtificalSUN** [comment]
Fixed
