### ISSUE TITLE
Команда M900 в коде для RRF.

### ISSUE THREAD

**Issue by kileug** [ArtificalSUN/Kcalibrator#21]
В коде сгенерированном для RRF вместо "M572 D0 S0" находится команда "M900 K0".
[KF_0.05-0.7-0.05_H200-B60.zip](https://github.com/ArtificalSUN/Kcalibrator/files/7822700/KF_0.05-0.7-0.05_H200-B60.zip)
.

**Comment by ArtificalSUN** [comment]
Fixed
