### ISSUE TITLE
Команда M900 в коде для Klipper

### ISSUE THREAD

**Issue by Nordicx86** [ArtificalSUN/Kcalibrator#23]
Собственно в результате  генерируется не рабочий код для клиппера.
Вобще возможно имеет смысл попытатmся интегрировать стандартную команду Для настройки от Klipper
" TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=ADVANCE START=0 FACTOR=.005 " 
https://github.com/Klipper3d/klipper/blob/master/docs/Pressure_Advance.md

**Comment by ArtificalSUN** [comment]
Fixed
