### ISSUE TITLE
Ошибка загрузки настроек при запуске приложения

### ISSUE THREAD

**Issue by ilmen** [ArtificalSUN/Kcalibrator#24]
При открытии приложения размер стола по Y заполняется из размера по X
Хотя в файле Kcalibrator.cfg хранился корректный размер стола по Y
![изображение](https://user-images.githubusercontent.com/1914708/152674628-ee88300f-ebc7-4a76-a8ed-4e38b311e8d8.png)

Шаги для воспроизведения:
1) выбрать Kinematics: cartesian
2) настроить разный размер для X и Y
3) щелкнуть Save configuration
4) закрыть приложения
5) проверить файл Kcalibrator.cfg на предмет верного размера по X и Y
6) запустить Kcalibrator.exe
7) удостовериться, что размер по Y заменился значением размера по X

**Comment by ArtificalSUN** [comment]
Fixed
