### ISSUE TITLE
(Linux) No dropdown items, no save setting etc

### ISSUE THREAD

**Issue by sacculus** [ArtificalSUN/Kcalibrator#32]
Hi
I tryed to run Kcalibrator under Fedora 36 x64 but not success.

```
$ python --version
Python 3.10.6

$ python kcalibrator_gui.py
```

All dropdown controls (Kinematics, Firmware, Autoleveling type) haven't any items to choose.
As result (as I understand) program doesn't save settings and doesn't generate G-code.
No any errors shown in console and GUI.

Tryed master and 1.0.4 release of Kconfigurator.

I'll wery thankful for help.

**Comment by ArtificalSUN** [comment]
Hi! Don't run kcalibrator_gui.py, it's the module that only generates UI. Instead run kcalibrator.pyw.
