### ISSUE TITLE
[wishlist] Add an k-factor calculation to the form.

### ISSUE THREAD

**Issue by trapeznikov-ap** [ArtificalSUN/Kcalibrator#6]
Add an k-factor calculation to the form. When generating a rcode, all the data has already been entered into the form. It remains only to substitute the height from the test print, and get the k-factor value.

**Comment by ArtificalSUN** [comment]
Thanks for the suggestion. This is basically the next thing I'm going to add to the tool.

**Comment by ArtificalSUN** [comment]
K-factor calculator added in v1.0.4
